version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/Dockerfile
      args:
        docker_id: ${DOCKER_UID}
        docker_user: ${DOCKER_USER}
    restart: unless-stopped
    user: ${DOCKER_USER}
    volumes:
      - ./app:/usr/src/app
      - ${GOPATH}/pkg:/go/pkg
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/dev.conf
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/pg-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432